### ISSUE TITLE
Фикси давай =)

### ISSUE THREAD

**Issue by aveBHS** [asyncvk/vkbee#1]
![изображение](https://user-images.githubusercontent.com/16632774/73651363-577b6f00-4695-11ea-8a60-54c13bcc620c.png)

**Comment by YamkaFox** [comment]
> ок будет сделано в 1.1

**Comment by YamkaFox** [comment]
FIXED 
VKBee with top!
`python ti pidor`

**Comment by YamkaFox** [comment]
`Closed!`
